apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sfe-devops-app-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: sfe-devops-app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
